config/routes.rb
Rails.application.routes.draw do
  resources :pockemons
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pockemon.rb
class Pockemon < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pockemons_controller.rb
class PockemonsController < ApplicationController
  before_action :set_pockemon, only: [:show, :edit, :update, :destroy]

  # GET /pockemons
  # GET /pockemons.json
  def index
    @pockemons = Pockemon.all
  end

  # GET /pockemons/1
  # GET /pockemons/1.json
  def show
  end

  # GET /pockemons/new
  def new
    @pockemon = Pockemon.new
  end

  # GET /pockemons/1/edit
  def edit
  end

  # POST /pockemons
  # POST /pockemons.json
  def create
    @pockemon = Pockemon.new(pockemon_params)

    respond_to do |format|
      if @pockemon.save
        format.html { redirect_to @pockemon, notice: 'Pockemon was successfully created.' }
        format.json { render :show, status: :created, location: @pockemon }
      else
        format.html { render :new }
        format.json { render json: @pockemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pockemons/1
  # PATCH/PUT /pockemons/1.json
  def update
    respond_to do |format|
      if @pockemon.update(pockemon_params)
        format.html { redirect_to @pockemon, notice: 'Pockemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pockemon }
      else
        format.html { render :edit }
        format.json { render json: @pockemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pockemons/1
  # DELETE /pockemons/1.json
  def destroy
    @pockemon.destroy
    respond_to do |format|
      format.html { redirect_to pockemons_url, notice: 'Pockemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pockemon
      @pockemon = Pockemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pockemon_params
      params.require(:pockemon).permit(:name, :desciption, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pockemons_helper.rb
module PockemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pockemons/_form.html.erb
<%= form_with(model: pockemon, local: true) do |form| %>
  <% if pockemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pockemon.errors.count, "error") %> prohibited this pockemon from being saved:</h2>

      <ul>
      <% pockemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pockemon_name %>
  </div>

  <div class="field">
    <%= form.label :desciption %>
    <%= form.text_field :desciption, id: :pockemon_desciption %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :pockemon_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pockemons/edit.html.erb
<h1>Editing Pockemon</h1>

<%= render 'form', pockemon: @pockemon %>

<%= link_to 'Show', @pockemon %> |
<%= link_to 'Back', pockemons_path %>

app/views/pockemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pockemons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desciption</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pockemons.each do |pockemon| %>
      <tr>
        <td><%= pockemon.name %></td>
        <td><%= pockemon.desciption %></td>
        <td><%= pockemon.user %></td>
        <td><%= link_to 'Show', pockemon %></td>
        <td><%= link_to 'Edit', edit_pockemon_path(pockemon) %></td>
        <td><%= link_to 'Destroy', pockemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pockemon', new_pockemon_path %>

app/views/pockemons/new.html.erb
<h1>New Pockemon</h1>

<%= render 'form', pockemon: @pockemon %>

<%= link_to 'Back', pockemons_path %>

app/views/pockemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pockemon.name %>
</p>

<p>
  <strong>Desciption:</strong>
  <%= @pockemon.desciption %>
</p>

<p>
  <strong>User:</strong>
  <%= @pockemon.user %>
</p>

<%= link_to 'Edit', edit_pockemon_path(@pockemon) %> |
<%= link_to 'Back', pockemons_path %>